# Generated by Django 2.2.7 on 2020-01-13 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id_anime', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('generos', models.CharField(max_length=50)),
                ('formato_emision', models.CharField(max_length=50)),
                ('numero_episodios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.TextField()),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Anime')),
            ],
        ),
    ]
